D_a: 64
D_s: 128
H_a: 128
H_c: 16
H_k: 256
H_s: 64
data_type: mnist
drop_out: 0.1
epochs: 50
lambda_l1: 1.0e-05
lr: 0.0005
mean_bag_length: 10
n_bag_center: 3
n_bag_density: 3
n_ins_center: 3
n_ins_density: 3
n_ins_mask: 3
n_mask: 10
n_sample: 10
net_type: dkmil
num_bags_test: 50
num_bags_train: 200
num_bags_vad: 50
params_config: null
r_mask: 0.1
seed: 1
target_number: 9
var_bag_length: 2
weight_decay: 5.0e-05
